# Generated by Django 3.2.9 on 2021-11-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('maxExtras', models.IntegerField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(null=True, upload_to='platillos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.categoria')),
            ],
        ),
    ]
