# Generated by Django 2.0.3 on 2021-12-02 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPlatillos', models.IntegerField()),
                ('precioPlatillos', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('maxExtras', models.IntegerField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(null=True, upload_to='platillos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platillos', to='orders.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Platillo'),
        ),
    ]
