# Generated by Django 3.2.9 on 2021-11-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPlatillos', models.IntegerField()),
                ('precioPlatillos', models.FloatField()),
                ('cantidadExtras', models.IntegerField()),
                ('id_extras', models.ManyToManyField(blank=True, to='orders.Extra')),
                ('id_platillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.pedido')),
            ],
        ),
    ]
