# Generated by Django 2.0.3 on 2021-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211126_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
